# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mandelRcpp <- function(x_min, x_max, y_min, y_max, res_x, res_y, nb_iter) {
    .Call(`_mandelExplorer_mandelRcpp`, x_min, x_max, y_min, y_max, res_x, res_y, nb_iter)
}

mandelRcpp2 <- function(x_min, x_max, y_min, y_max, res_x, res_y, nb_iter) {
    .Call(`_mandelExplorer_mandelRcpp2`, x_min, x_max, y_min, y_max, res_x, res_y, nb_iter)
}

mandelsmoothRcpp <- function(x_min, x_max, y_min, y_max, res_x, res_y, nb_iter) {
    .Call(`_mandelExplorer_mandelsmoothRcpp`, x_min, x_max, y_min, y_max, res_x, res_y, nb_iter)
}

mandelsmoothRcpp2 <- function(x_min, x_max, y_min, y_max, res_x, res_y, nb_iter) {
    .Call(`_mandelExplorer_mandelsmoothRcpp2`, x_min, x_max, y_min, y_max, res_x, res_y, nb_iter)
}

